name: Deploy frontend-stage to Staging Google App Engine

on:
  push:
    branches:
      - main
    tags:
      - 'frontend-*'
  workflow_dispatch:

env:
  PROJECT_ID: 'manuelmata-dev'
  APP_ENV: 'staging'

jobs:
  deploy:
    name: Deploy Frontend to Google App Engine
    runs-on: ubuntu-latest
    environment: frontend-stage
    defaults:
      run:
        working-directory: .
    permissions:
      contents: read
      id-token: write
    if: |
      github.ref == 'refs/heads/main' ||
      (startsWith(github.ref, 'refs/tags/frontend-') && !endsWith(github.ref, '-prod'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the Frontend
        run: pnpm build

      - name: Authorize Google Cloud SDK
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.CREDENTIALS_JSON }}'

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          deliverables: frontend-stage.yaml
